name: Copy Directory to gh-pages

on:
  push:
    branches:
      - main

jobs:
  copy-directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Remove existing files in gh-pages branch
        run: git rm -rf .

      - name: Copy directory from main to gh-pages
        run: cp -a ./example-book .

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Copy directory from main to gh-pages"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
