name: Copy Directory to gh-pages

on:
  push:
    branches:
      - main

jobs:
  copy-directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install git
        run: sudo apt-get install git -y

      - name: Copy directory to gh-pages branch
        run: |
          git clone --branch gh-pages --single-branch https://github.com/${GITHUB_REPOSITORY} gh-pages
          cp -a example-book/. gh-pages/
          cd gh-pages
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Copy directory from main to gh-pages"
          git push origin gh-pages
