name: Copy build to gh_pages   

on: [push]

jobs:
  copy:
    name: Copy my folder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy
        env:
          SRC_FOLDER_PATH: 'example-book/book/'
          TARGET_BRANCH: 'gh_pages'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
        
          # Copy all files from source directory to the current directory
          cp -r "$SRC_FOLDER_PATH"/* ./
        
          # Stage all copied files
          git add .
        
          # Commit and push changes
          git diff-index --quiet HEAD || git commit -am "Deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch
